# Generated by Django 3.0.4 on 2020-06-06 12:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('corporate_email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.IntegerField()),
                ('job_title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('request_type', models.CharField(blank=True, choices=[('Request Sample', 'Request Sample'), ('Request Discount', 'Request Discount'), ('Request Inquiry', 'Request Inquiry')], max_length=30, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
        ),
    ]
