# Generated by Django 3.0.4 on 2020-06-06 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
