# Generated by Django 3.0.4 on 2020-06-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200608_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
