# Generated by Django 3.0.4 on 2020-06-20 03:29

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_us',
            name='contact_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 20, 3, 29, 42, 7680, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
