# Generated by Django 3.0.4 on 2020-07-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20200620_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing_details',
            options={'verbose_name_plural': 'BillingDetails'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
